[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10


[environments.production]
variables = { 
  DJANGO_SETTINGS_MODULE = "calendario_reservas.settings_production",
  DEBUG = "False",
  RAILWAY_ENVIRONMENT = "production"
}