services:
  - type: web
    name: calendario-saipe
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn calendario_reservas.wsgi:application --timeout 120 --workers 1 --max-requests 500 --max-requests-jitter 50
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: calendario_reservas.settings_production
      - key: DATABASE_URL
        value: postgresql://postgres.twpoddtqdxqlayepmtts:QfWo5LMTB1XKB0qW@aws-1-us-east-1.pooler.supabase.com:5432/postgres
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.0

