# Generated by Django 5.2.6 on 2025-09-16 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='calendario__fecha_i_a3c8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['recurso', 'estado'], name='calendario__recurso_ef99b4_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['usuario', 'fecha_inicio'], name='calendario__usuario_71e8ee_idx'),
        ),
    ]
