# Generated by Django 5.2.6 on 2025-09-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('en_curso', 'En curso'), ('terminada', 'Terminada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20, verbose_name='Estado'),
        ),
    ]
