# Generated by Django 5.2.6 on 2025-09-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_update_reserva_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='descripcion_detallada',
            field=models.TextField(blank=True, help_text='Descripción completa de la sala con características y equipamiento', verbose_name='Descripción detallada'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='horario_uso',
            field=models.CharField(blank=True, help_text='Ej: Lunes a Viernes de 7:00 AM a 4:00 PM', max_length=200, verbose_name='Horario de uso'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='tiene_audio',
            field=models.BooleanField(default=False, verbose_name='Sistema de audio'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='tiene_climatizacion',
            field=models.BooleanField(default=False, verbose_name='Climatización'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='tiene_pizarra',
            field=models.BooleanField(default=False, verbose_name='Pizarra blanca'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='tiene_proyector',
            field=models.BooleanField(default=False, verbose_name='Proyector HD'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='tiene_videoconferencia',
            field=models.BooleanField(default=False, verbose_name='Videoconferencia'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='tiene_wifi',
            field=models.BooleanField(default=False, verbose_name='WiFi de alta velocidad'),
        ),
    ]
