# Generated by Django 5.2.6 on 2025-09-29 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_recurso_descripcion_detallada_recurso_horario_uso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del vehículo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('patente', models.CharField(max_length=10, unique=True, verbose_name='Patente')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('capacidad_pasajeros', models.PositiveIntegerField(default=5, verbose_name='Capacidad de pasajeros')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='VehiculoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_desde', models.TimeField(verbose_name='Hora desde')),
                ('hora_hasta', models.TimeField(verbose_name='Hora hasta')),
                ('responsable', models.CharField(max_length=200, verbose_name='Responsable')),
                ('destino', models.CharField(max_length=300, verbose_name='Destino')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción adicional')),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('en_curso', 'En curso'), ('terminada', 'Terminada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendario.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Reserva de Vehículo',
                'verbose_name_plural': 'Reservas de Vehículos',
                'ordering': ['-fecha', '-hora_desde'],
                'indexes': [models.Index(fields=['fecha', 'hora_desde', 'hora_hasta'], name='calendario__fecha_d5dbba_idx'), models.Index(fields=['vehiculo', 'estado'], name='calendario__vehicul_da7a06_idx'), models.Index(fields=['usuario', 'fecha'], name='calendario__usuario_dd9f91_idx')],
            },
        ),
    ]
