# Generated by Django 5.2.6 on 2025-09-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_vehiculo_vehiculoreserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculoreserva',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='vehiculoreserva',
            name='usuario',
        ),
        migrations.AddField(
            model_name='recurso',
            name='marca',
            field=models.CharField(blank=True, max_length=50, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='patente',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Patente'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='tipo',
            field=models.CharField(choices=[('sala', 'Sala de Reunión'), ('vehiculo', 'Vehículo')], default='sala', max_length=20, verbose_name='Tipo de recurso'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='destino',
            field=models.CharField(blank=True, max_length=300, verbose_name='Destino'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='responsable',
            field=models.CharField(blank=True, max_length=200, verbose_name='Responsable'),
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
        migrations.DeleteModel(
            name='VehiculoReserva',
        ),
    ]
