# Generated by Django 5.2.6 on 2025-09-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0005_remove_vehiculoreserva_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título'),
        ),
    ]
