# Generated by Django 5.2.6 on 2025-09-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0006_alter_reserva_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_vuelta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vuelta'),
        ),
    ]
